### ISSUE TITLE
Hi There I got issue about webhook.send()

### ISSUE THREAD

**Issue by NicoChang96** [bitcanon/synochat#1]
Hi, First, Thank you develop this package, I have a question, Could you help me?
When I added webhook. send('hi') in my flask app, I got the error message "requests. exceptions.SSLError",
And I  google for this problem all for "requests" for this package. but It didn't fix my problem.
Do you have any suggestions for me?

**Comment by NicoChang96** [comment]
already fixed it

**Comment by bitcanon** [comment]
Hi, thanks for using this package. Glad to hear that you solved the issue, I have been quite busy at the moment so I just saw your message. Hope it works for you :)
