### ISSUE TITLE
file url no response

### ISSUE THREAD

**Issue by park-seokjae** [bitcanon/synochat#2]
There is no response from the Add Images and Files command. 

Can confirm my command? 

------------------------------------------------------------------------------------------
from flask import Flask, request

from synochat.webhooks import SlashCommand

from synochat.exceptions import *

app = Flask(__name__)

@app.route('/slash', methods=['POST'])

def slash():

	token   = 'CPCk2yhYTLpChqtOX5UXDSj2zpg6awHdqBNx50jfWpB6QNNyQHFp5pEUtqmx21NQ'

	command = SlashCommand(request.form)

	if not command.authenticate(token):

		return command.createResponse('잘못된 토큰.')

	return command.createResponse('Send text with a photo attached.', file_url='https://www.synology.com/img/company/branding/synology_logo.jpg')

if __name__ == '__main__':

   app.run('0.0.0.0', port=4000, debug = True)

------------------------------------------------------------------------------------------
![다운로드 (1)](https://user-images.githubusercontent.com/58238480/191648328-c686ad4d-d97f-47ee-8f03-7a30db3a3ffa.png)

When called with the slash command, only text is displayed and the url command containing a file is excluded. 

Images to be included : file_url='https://www.synology.com/img/company/branding/synology_logo.jpg'

**Comment by bitcanon** [comment]
Hi, I think I have had some issues with this as well. And from what I could find out there can be two issues.
1. Your NAS is unable to resolve the domain name www.synology.com
2. The image being downloaded has an invalid file format and is just ignored by the char server.

This file should be downloadable so I suspect a DNS issue. You could check the **Control Panel>Network>General** tab and make sure that you have configured a DNS-server.

If you have SSH enabled you could also `ssh` into the NAS and run `wget https://www.synology.com/img/company/branding/synology_logo.jpg` and see if that works.

Please let me know how it goes.

**Comment by park-seokjae** [comment]
Hi, I tried again after running the wget command on SSL, but still couldn't load the image.
I think the file_url command doesn't seem to work. The reason is that even if the image url address is applied to a different address, the image or file is not attached in the same way.
Are there any commands that were attached during testing?
If yes, please let me know. I'll test the same.

thank you

**Comment by bitcanon** [comment]
What was the result of the wget command when running it on the ssh session on the NAS?

**Comment by park-seokjae** [comment]
![image](https://user-images.githubusercontent.com/58238480/192198210-696a7bc3-1ded-4f8d-acc5-866e5afe6df6.png)

from flask import Flask, request

from synochat.webhooks import SlashCommand
from synochat.exceptions import *
a = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"
app = Flask(__name__)

@app.route('/slash', methods=['POST'])
def slash():
	token   = 'CPCk2yhYTLpChqtOX5UXDSj2zpg6awHdqBNx50jfWpB6QNNyQHFp5pEUtqmx21NQ'
	command = SlashCommand(request.form)

	if not command.authenticate(token):
		return command.createResponse('잘못된 토큰.')

	return command.createResponse('a', file_url='https://geomedical.co.kr/test/food.png')

if __name__ == '__main__':
   app.run('0.0.0.0', port=4000, debug = True)

![image](https://user-images.githubusercontent.com/58238480/192198234-86561525-455c-4d38-a206-ba7d4df15e3c.png)

same..

**Comment by bitcanon** [comment]
Hm, you seem to have a lot of certificate issues when fetching over HTTPS. Is the system clock on your NAS in sync?
(I will do some testing with the URLs you provided a bit later and see if there is a problem with the library)

**Comment by bitcanon** [comment]
So, I have looked into your issue and found out that the Synology Chat API server doesn't support the `file_url` parameter in the response to a slash command. 

The documentation of slash commands in the Synology Chat help center is pretty much **none existent**: 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/76094372/192216728-93cb5a85-183a-4a92-9814-11ad85c3fb58.png">
Source: https://kb.synology.com/sv-se/DSM/help/Chat/chat_integration?version=7

The API simply ignores the `file_url` parameter and sadly there is not much I can do about this but to remove the `file_url` parameter from the `createResponse()` method.
