### ISSUE TITLE
any advice on msg too long exception?

### ISSUE THREAD

**Issue by guanlisheng** [bitcanon/synochat#4]
as subject, do you have any idea to get/set the limit?

**Comment by bitcanon** [comment]
Hi, I have never stumbled upon that exception. Please post the exception output and also an example input that will raise the exception.
Until a fix may be released you can do a simple check and just show an error message your self or maybe truncate the subject if it's too long.

**Comment by guanlisheng** [comment]
thanks, I manually determined it is about 2000 characters. going to close this issue

FYI: the background is that I wanted to integrate LLM locally into Synology Chat, called [synochatgpt](https://github.com/guanlisheng/synochatgpt), and found LLM may return a longer response than Synology Chat can accept.
